language: node_js
node_js:
  - node

services:
- docker

env:
  global:
  - IMAGE_NAME=cisneiros/cisne.dev
  - M2_LOCATION=/root/.m2
  - NODE_MODULES_LOCATION=/app/node_modules
  - OUT_LOCATION=/app/target/production
  - secure: SxgEqcfTQN/lJkvANXDhb5nW7RCam8feLBNgI1DTEJrw74BvlxxyVHM6ObVBe8Ihw8Cf/KjNL8kaFtjJyldOoJTy9o7LeIxt+Ln/bqjOP4MdNjb8lyTZyVxzx+WJF4pzLV53SCPYCkxLkFYpIv5skPm2IDspPC7OmdcGH3El6837BdjRf31BpwgG3qIKBphgx/0v+kh4QA/BjICExw/l3o1Sz2qTk0xbUfHQJO7/zMahPFqTFhOPLqBSF6ZNlX1aYb0gNoKpKx75E/tzpFObrk6qpc55ciNqvJqWgpNAK8HBLSwOagtqpZQr4n0jLMYyPGotly3pxXReDEGxpEA9Cu8bM0a2ylbEnE4Q27iIhsaPQyypyn2dUR4ZVLu2gqrBc2fDdskALbQWZbU48Nui/EaXVRDngbXFkMhr0SA1vLYymqYuL7tecjbA5RvSTFo9Tg5l9TJL4uvubZtsDnPCHEaIKyobpYB/gS4t3sypNKNVQM9GnV1TQG4mGd557yvwOCmysWiFPwx29AFiafwwJDulztCgyePfBMjg0XVeXopmvsxjXkhlF9XtoVWWV8K7zuTdglbZi//6c/liyZ8CYe9xrT4NBzb4a/xPgzDYvQJchSuDfjiZDGj0v+f/ZeEU7omCPmOOQGCgABOutvbj4Ntpsd1Q7LUg6m9NQbezvOE=
  - secure: Ij4d1xO5LMIh480ggDId52pPtgqxs1o3hkIbemFmD3IxUMoU9rxg0nTfM0uJwKXy5Bq7tUdeC9ThGdJEMnCg0e1/mpfos49AaMoQ/hnKJM6iqMTQ9QiWFwHl24KkDE1AGIcIHECONVR87LY3B1+WZuc5YI2ybpfo1hmop3/Ica3RlWiNmR1V0Zq1MpDpueoWgLM6r2GErPb1alIQ5f4adfWcPoKnllqhPLV9Izrq6RO0xEl4uuur3JEdOtzHVrI8Oka3lnNZazuAwz8NHl15Z0ubHRRBirJTVHhP5gXhwHh6AMzW9hd4smgqK/zQxIsF6ipjUq4rfGbyT1or7zt5mX3kRtR1qppe5xfYIzOusBZ/OaLktoswswyACUZQf9591GvA+vqUjppfMz9F/qkE+x3Rjfbf7RYLJ5rQ+uY8m2AJ0wFD9DSRGd3di+cH6Q6JKrNSDgpt+yT16h66FXPUdBLC/6AVH94vxoSJPPgDlHMudOxzV+mrgurCR0NFCh6PrMUdANuAiF+mryURmees29vbIwJAQGvwuijngmHEkgLFGr4T1dhacG7bR+hHVd7q2o/szU7U8O7LC8yMAUy6O+Cy4i3NSZyo2xM674ImPWId7LKFSd+c+7mtNcGnteiOE9Opjr9yZx/z0iuEGmoCSM8YiUrSMPvqGwCM6gZDdr0=
  - secure: Eo+QCJljwxIq2HnXtcRhnWW6izpcxLwPjljD/MQQxKFIh1b703rGCZ/AEtFohtK8lOO6w3gGG4HV2W2EmpstJXQ4lg9/s9I/934kGcKP71zNwLo9UbRmbSOAKJV8HvclT8Bw8r+zTikKwkbHOIkukZer+z4ey0kcdodfrvjlIFR+YDFIzyJsjQ8RdaJ3Y71NnGL6rcBG6NUo4BbsrJoYg/hQZY9bWqoCz5oIUVjhz/o6rYjUXoCck6+GXlFnQ36wiesxfpphxagbsCPcFZ9oG75PIt7JBtjUYqd07Of/VArX1uXQao4EFv+uYSYEHRwksZH+5qeL0RVaxO28eVb1QmmNZ9pvjvyTCqhsjGpT/w6maPZgtILIMp3fWnB/Ti8YrWFipH4XCi9+LTVtw/ir7pRDe0AmO/4jQH3kp8jg1tPMRWYqnAwf4RukDdF2R50wkTKGco56Xm9W8RKG+3KwMXIXTr3noAE8NScT5lOSBC8sUeUc6aDTr/BIyu05m4cSO4PFDZQtv+ji700pblRCnzae5jxUtehnWOxmft0GZeeyR4O5I5Mxycjlsfv5UwIlnCcs/XFm4SJS0TJAus7gUj2NU+O0ChedAtRfBNBEPtUgtoeAn3aCYRTaN2ubovvdBR5L7e3JjZjhJtyAt4sOnmNyS67ENGg5A7UHYDn3W5Q=

cache:
  directories:
  - .cache

before_install:
- npm i -g now
- docker build --target deps -t ${IMAGE_NAME}:deps .

install:
- docker run --volume=${PWD}/.cache/m2:${M2_LOCATION} --volume=${PWD}/.cache/node_modules:${NODE_MODULES_LOCATION}
  ${IMAGE_NAME}:deps

before_script:
- docker build --target test -t ${IMAGE_NAME}:test .
- docker build --target build -t ${IMAGE_NAME}:build .

script:
- docker run --rm -it ${IMAGE_NAME}:test
- docker run --rm -it --volume=${PWD}/out:${OUT_LOCATION} ${IMAGE_NAME}:build
- .travis/deploy-preview.sh

branches:
  only:
    - master

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    committer_from_gh: true
    local_dir: out
    fqdn: cisne.dev
    on:
      branch: master
