language: node_js
node_js:
  - node

services:
- docker

env:
  global:
  - IMAGE_NAME=cisneiros/cisne.dev
  - M2_LOCATION=/root/.m2
  - NODE_MODULES_LOCATION=/app/node_modules
  - OUT_LOCATION=/app/target/production
  - secure: LZZ7hAcpyPOix86geVuN8y6TbkqR7wbvJ4vtJzI2oPG/ukUyHo361uvjDHGdxRejt0zSbzITjEemZ/3Ltc0Lh9+M40S35VpPIktPNVDXoJkOsLb1yv5lxDI0faztQprPk6Sq6RHAO/kXdxZrw7rJRx75Epiq7iIoqJT8TwNI7chDHMo8cVzmbSm+kK/wSLOA2h+0ADFWGK8dKYMS4J4ZwJ8N1oDsBWdlCCXI/wSpZYXkDoN/ZOse8VJrui95415oVCe2oh56wJTwXLShX/HxmrKTmetImgNB0bLBKujrvUMcleZHTh8G7LP3J2SPLqsH45Q2hOBNP5e+qFOv3gf+95PB2acjt0Zahyv2dAmkuelg3GfZRPHcikr58wlzouf0Wfmv+SC/NWEE4AkU2U2gL+rqj+7OikAWxE+LgHzPzJAng7x2tyB6vaQE0ZW1VxRHmmeGObKUPLel0hlFubBwKIodFbMYLu81IR5rOeu1zlhSd4s+y9zq0wwpgcSorLf/U++60DKSX/OCOavRBLPcPziRn+OEsaf5CgcJh+zKShBEBg4fS3B2AIPjSxYN3cHHFFZuthcbgOuBxVB/LMExcHA1yGkHzz1Q984kbp32hwi2YDIcEiIGUmjZoj3Q8tYfmdNGvt1EkUr8L8PsUlzMllbK2abNpddzxqgihnsWN/g=
  - secure: Ij4d1xO5LMIh480ggDId52pPtgqxs1o3hkIbemFmD3IxUMoU9rxg0nTfM0uJwKXy5Bq7tUdeC9ThGdJEMnCg0e1/mpfos49AaMoQ/hnKJM6iqMTQ9QiWFwHl24KkDE1AGIcIHECONVR87LY3B1+WZuc5YI2ybpfo1hmop3/Ica3RlWiNmR1V0Zq1MpDpueoWgLM6r2GErPb1alIQ5f4adfWcPoKnllqhPLV9Izrq6RO0xEl4uuur3JEdOtzHVrI8Oka3lnNZazuAwz8NHl15Z0ubHRRBirJTVHhP5gXhwHh6AMzW9hd4smgqK/zQxIsF6ipjUq4rfGbyT1or7zt5mX3kRtR1qppe5xfYIzOusBZ/OaLktoswswyACUZQf9591GvA+vqUjppfMz9F/qkE+x3Rjfbf7RYLJ5rQ+uY8m2AJ0wFD9DSRGd3di+cH6Q6JKrNSDgpt+yT16h66FXPUdBLC/6AVH94vxoSJPPgDlHMudOxzV+mrgurCR0NFCh6PrMUdANuAiF+mryURmees29vbIwJAQGvwuijngmHEkgLFGr4T1dhacG7bR+hHVd7q2o/szU7U8O7LC8yMAUy6O+Cy4i3NSZyo2xM674ImPWId7LKFSd+c+7mtNcGnteiOE9Opjr9yZx/z0iuEGmoCSM8YiUrSMPvqGwCM6gZDdr0=
  - secure: Eo+QCJljwxIq2HnXtcRhnWW6izpcxLwPjljD/MQQxKFIh1b703rGCZ/AEtFohtK8lOO6w3gGG4HV2W2EmpstJXQ4lg9/s9I/934kGcKP71zNwLo9UbRmbSOAKJV8HvclT8Bw8r+zTikKwkbHOIkukZer+z4ey0kcdodfrvjlIFR+YDFIzyJsjQ8RdaJ3Y71NnGL6rcBG6NUo4BbsrJoYg/hQZY9bWqoCz5oIUVjhz/o6rYjUXoCck6+GXlFnQ36wiesxfpphxagbsCPcFZ9oG75PIt7JBtjUYqd07Of/VArX1uXQao4EFv+uYSYEHRwksZH+5qeL0RVaxO28eVb1QmmNZ9pvjvyTCqhsjGpT/w6maPZgtILIMp3fWnB/Ti8YrWFipH4XCi9+LTVtw/ir7pRDe0AmO/4jQH3kp8jg1tPMRWYqnAwf4RukDdF2R50wkTKGco56Xm9W8RKG+3KwMXIXTr3noAE8NScT5lOSBC8sUeUc6aDTr/BIyu05m4cSO4PFDZQtv+ji700pblRCnzae5jxUtehnWOxmft0GZeeyR4O5I5Mxycjlsfv5UwIlnCcs/XFm4SJS0TJAus7gUj2NU+O0ChedAtRfBNBEPtUgtoeAn3aCYRTaN2ubovvdBR5L7e3JjZjhJtyAt4sOnmNyS67ENGg5A7UHYDn3W5Q=

cache:
  directories:
  - .cache

before_install:
- npm i -g now
- docker build --target deps -t ${IMAGE_NAME}:deps .

install:
- docker run --volume=${PWD}/.cache/m2:${M2_LOCATION} --volume=${PWD}/.cache/node_modules:${NODE_MODULES_LOCATION}
  ${IMAGE_NAME}:deps

before_script:
- docker build --target test -t ${IMAGE_NAME}:test .
- docker build --target build -t ${IMAGE_NAME}:build .

script:
- docker run --rm -it ${IMAGE_NAME}:test
- docker run --rm -it --volume=${PWD}/out:${OUT_LOCATION} ${IMAGE_NAME}:build
- .travis/deploy-preview.sh

branches:
  only:
    - master

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    committer_from_gh: true
    local_dir: out
    on:
      branch: master
